function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=params(40);
    ys_(2)=params(41);
    ys_(3)=params(42);
    ys_(4)=params(43);
    ys_(15)=1;
    ys_(5)=params(44);
    ys_(6)=params(45);
    ys_(12)=1;
    ys_(7)=params(47);
    ys_(8)=params(48);
    ys_(9)=params(49);
    ys_(10)=params(50);
    ys_(13)=1;
    ys_(14)=1;
    ys_(16)=params(51);
    ys_(17)=params(52);
    ys_(18)=params(54);
    ys_(19)=params(58);
    ys_(20)=params(57);
    ys_(21)=params(59);
    ys_(11)=params(60);
    ys_(22)=params(17)*params(20)/(params(41)*(1-params(17)*(1-params(16))));
    % Auxiliary equations
ys_(54)=ys_(26);
ys_(55)=ys_(26);
ys_(56)=ys_(26);
ys_(57)=ys_(26);
ys_(58)=ys_(26);
ys_(59)=ys_(26);
ys_(60)=ys_(26);
ys_(61)=ys_(26);
ys_(62)=ys_(26);
ys_(63)=ys_(26);
end
